// MindlessSpot -- minimal single-fixture DMX spotlight controller.
//
// Hardware: Arduino UNO R4 WiFi, Modulino Joystick, Modulino Knob, Whadda
// DMX512 module (driven from Serial1 TX, pin 1).
//
// The joystick moves pan/tilt at a speed proportional to its deflection
// Turning the knob changes the dimmer. All settings are hard coded below.

#include <Arduino.h>
#include <Arduino_Modulino.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Fixture settings (1-based DMX channels)
// ---------------------------------------------------------------------------
constexpr uint16_t PAN_CHANNEL = 1;
constexpr uint16_t TILT_CHANNEL = 3;
constexpr uint16_t DIMMER_CHANNEL = 12;

constexpr uint8_t PAN_DMX_MIN = 110;
constexpr uint8_t PAN_DMX_MAX = 160;
constexpr uint8_t TILT_DMX_MIN = 40;
constexpr uint8_t TILT_DMX_MAX = 60;

constexpr bool PAN_INVERT = false;
constexpr bool TILT_INVERT = false;

struct StaticChannel {
  uint16_t channel;
  uint8_t value;
};

// Channels that always carry a fixed value (shutter open, color wheel, ...).
constexpr StaticChannel STATIC_CHANNELS[] = {
  {5, 0},
  {6, 120},
  {11, 255},
  {13, 4}
};

// ---------------------------------------------------------------------------
// Control tuning
// ---------------------------------------------------------------------------
// Full joystick deflection sweeps the whole min..max range in this time.
constexpr float FULL_SWEEP_SECONDS = 1.0f;
constexpr int16_t JOYSTICK_DEADZONE = 8;
constexpr int16_t JOYSTICK_FULL_SCALE = 127;

constexpr int16_t DIMMER_STEP_PER_KNOB_TICK = 5; // percent
constexpr int16_t DIMMER_START_PERCENT = 0;

// ---------------------------------------------------------------------------
// DMX output
// ---------------------------------------------------------------------------
#if defined(PIN_SERIAL1_TX)
constexpr uint8_t DMX_TX_PIN = PIN_SERIAL1_TX;
#else
constexpr uint8_t DMX_TX_PIN = 1;
#endif
constexpr uint16_t DMX_BREAK_US = 120;
constexpr uint16_t DMX_MAB_US = 12;
constexpr unsigned long DMX_KEEPALIVE_MS = 200;

ModulinoJoystick joystick;
ModulinoKnob knob;

uint8_t dmxFrame[513];
uint8_t sentFrame[513];
uint16_t dmxFrameLength = 1;
unsigned long lastDmxSendMs = 0;

// Normalized 0..1 position within each axis' min..max range.
float panPos = 0.5f;
float tiltPos = 0.5f;
int16_t dimmerPercent = DIMMER_START_PERCENT;
int16_t lastKnobValue = 0;
unsigned long lastLoopMs = 0;

void setChannel(uint16_t channel, uint8_t value) {
  if (channel >= 1 && channel <= 512) {
    dmxFrame[channel] = value;
    if (channel > dmxFrameLength) {
      dmxFrameLength = channel;
    }
  }
}

uint8_t axisToDmx(float pos, uint8_t minValue, uint8_t maxValue) {
  return static_cast<uint8_t>(minValue + (maxValue - minValue) * pos + 0.5f);
}

// Gamma-corrected so the knob feels linear to the eye.
uint8_t dimmerToDmx(int16_t percent) {
  float n = constrain(percent, 0, 100) / 100.0f;
  return static_cast<uint8_t>(n * n * 255.0f + 0.5f);
}

float joystickRate(int16_t raw) {
  if (abs(raw) < JOYSTICK_DEADZONE) {
    return 0.0f;
  }
  return constrain(raw / static_cast<float>(JOYSTICK_FULL_SCALE), -1.0f, 1.0f);
}

void buildFrame() {
  memset(dmxFrame, 0, sizeof(dmxFrame));
  for (const StaticChannel &s : STATIC_CHANNELS) {
    setChannel(s.channel, s.value);
  }
  setChannel(PAN_CHANNEL, axisToDmx(panPos, PAN_DMX_MIN, PAN_DMX_MAX));
  setChannel(TILT_CHANNEL, axisToDmx(tiltPos, TILT_DMX_MIN, TILT_DMX_MAX));
  setChannel(DIMMER_CHANNEL, dimmerToDmx(dimmerPercent));
}

bool frameNeedsSend() {
  return memcmp(dmxFrame, sentFrame, sizeof(dmxFrame)) != 0 ||
         (millis() - lastDmxSendMs) >= DMX_KEEPALIVE_MS;
}

// Break/MAB are generated by briefly taking the TX pin away from the UART.
void sendFrame() {
  Serial1.flush();
  Serial1.end();
  pinMode(DMX_TX_PIN, OUTPUT);
  digitalWrite(DMX_TX_PIN, LOW);
  delayMicroseconds(DMX_BREAK_US);
  digitalWrite(DMX_TX_PIN, HIGH);
  delayMicroseconds(DMX_MAB_US);
  Serial1.begin(250000, SERIAL_8N2);

  for (uint16_t i = 0; i <= dmxFrameLength; ++i) {
    Serial1.write(dmxFrame[i]);
  }

  memcpy(sentFrame, dmxFrame, sizeof(dmxFrame));
  lastDmxSendMs = millis();
}

void readKnob() {
  int16_t value = knob.get();
  int16_t delta = value - lastKnobValue;
  lastKnobValue = value;
  if (delta != 0) {
    dimmerPercent = constrain(dimmerPercent + delta * DIMMER_STEP_PER_KNOB_TICK, 0, 100);
  }
}

void readJoystick(float dtSeconds) {
  float step = dtSeconds / FULL_SWEEP_SECONDS;
  // The Modulino Joystick is mounted rotated: its Y axis is horizontal.
  float panRate = joystickRate(joystick.getY());
  float tiltRate = joystickRate(joystick.getX());
  if (PAN_INVERT) panRate = -panRate;
  if (TILT_INVERT) tiltRate = -tiltRate;
  panPos = constrain(panPos + panRate * step, 0.0f, 1.0f);
  tiltPos = constrain(tiltPos + tiltRate * step, 0.0f, 1.0f);
}

void setup() {
  Serial.begin(115200);
  Serial1.begin(250000, SERIAL_8N2);

  Modulino.begin();
  joystick.begin();
  knob.begin();
  lastKnobValue = knob.get();

  // Force the first frame out immediately.
  memset(sentFrame, 0xFF, sizeof(sentFrame));
  lastLoopMs = millis();
}

void loop() {
  joystick.update();

  unsigned long nowMs = millis();
  float dtSeconds = constrain((nowMs - lastLoopMs) / 1000.0f, 0.001f, 0.2f);
  lastLoopMs = nowMs;

  readKnob();
  readJoystick(dtSeconds);
  buildFrame();

  if (frameNeedsSend()) {
    sendFrame();
  } else {
    delay(2);
  }
}
